v0.16: htonl(), ntohl() replaced with dummy macros 	+ cpantesters win32 builds now failing with "svdutil.o:svdutil.c:(.text+0xabd): undefined reference to `htonl'" 	+ replacing netinet/in.h htonl() and ntohl() calls with dummy macros, since they're not really used here
git-svn-id: file:///home/moocow/svn/public/diss-perl/trunk/PDL-SVDLIBC@2384 097f6656-c427-11dc-a790-1b5d5187385a